### ISSUE TITLE
普罗米修斯:监控自发现逻辑只能放到 pod或service里，

### ISSUE THREAD

**Issue by derek0377** [derek0377/k8s#28]
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: cluster-master
spec:
  replicas: 3
  selector:
    name: cluster-master
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9121"
        prometheus.io/scrape: "true"
```
